version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo-compose
    restart: unless-stopped
    ports:
      - "27017:27017"          # maps container port 27017 to host
    volumes:
      - mongo-data:/data/db    # persistent data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  backend:
    build: .
    container_name: nodevault-backend
    restart: unless-stopped
    ports:
      - "3000:3000"           # maps container port 3000 to host
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/nodevault?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data:
